### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by Saqibi4213**
IN this project  which is SURVEY-FORM 
 I coded html and for some extra design and making my  project little more good i just coded some styling css code 
and i enjoy and learn alot from it 
creater survey-form
added some new files 
Html
Css

### CODE REVIEW

**Comment by ahzamir** [comment]
Hey @Saqibi4213 
- You did not set up the linters correctly so I can not provide you feedback first add linters and then request again for a review by mentioning me here in a comment using my username @ahzamir.

### Your issue:
- As I see you added `.hintrc` and `.stylelintrc.json` files inside the `.github` folder which is wrong, and also your `.workflow.yml` file is empty so it will not work.
- To solve this move these two files to one folder back in the root direction of your project.
- And you can copy the code for your `.workflow.yml` from `html-css` folder in the listers lesson from the drive.

Screenshot 2024-05-17 005300

**Comment by Saqibi4213** [comment]
resolving linter errors 
Stylelint error solved 
solved webhint error 
@ahzamir please visit my project and repo again ,
 thank you !

**Comment by ahzamir** [comment]
### Hi @Saqibi4213 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Copy your HTML file code and paste it to the freecodecamp website survey form project to see which requirements your project is missing solve those missing requirements and mention me here using @ahzamir to re-review your project.
- Well done by solving the linters issues. 🎯

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

AlmostThereReachGIF

 ## Highlights 🌞
 
🎯 Great Design implemented.
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
❌ You have followed and completed the Survey Form and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by Saqibi4213** [comment]
hello Sir 
I do some changes that required in my html file and add all requirement to my html file and run in freecodecamp also thier is no error and thick marked 
please do review my project and repo again and give me feedback thank you sir  @ahzamir

**Review by ahzamir — APPROVED** [review]
### Hi @Saqibi4213 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image


# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

GreatJobThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Odin project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
